version: "3.4"

services:
  analytics-frontend:
    build:
      context: "../../"
      dockerfile: ./docker/docker_production/Dockerfile
    container_name: analytics_frontend
    environment:
      REACT_APP_BASEURL: https://localhost:470/
#      REACT_APP_BASEURL: http://10.129.150.120:7000/
      HTTPS: true
      SSL_CRT_FILE: ./docker/certs/self_ssl.pem
      SSL_KEY_FILE: ./docker/certs/self_ssl_key.pem
    image: analytics_frontend
    restart: always
    ports:
      - "3005:3000"
