version: "3.4"

services:
  analytics-frontend:
    build:
      context: ".."
      dockerfile: ./docker/Dockerfile
    container_name: analytics_frontend
    environment:
      REACT_APP_BASEURL: http://localhost:8000/
    image: analytics_frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - mri-freesurfer-network
      - analytics-network
