version: "3.4"

services:
  analytics-frontend:
    build:
      context: ".."
      dockerfile: ./docker/Dockerfile
    container_name: analytics_frontend
    image: analytics_frontend
    restart: always
    ports:
      - "3005:3000"
