apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\mkont\WebstormProjects\data-analytics-and-visualisation-frontend\docker\kompose.exe convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: analytics-frontend
  name: analytics-frontend
spec:
  type: LoadBalancer
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: analytics-frontend
status:
  loadBalancer:
    ingress:
      - ip: 192.0.2.127
